sonar.projectKey=ysp
sonar.projectName=YSP Platform
sonar.organization=blitzz21
sonar.sources=app,src,components,lib
sonar.exclusions=node_modules/**,.next/**,coverage/**,playwright-report/**,test-results/**,**/*.spec.ts,**/*.test.ts
sonar.tests=tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.node.maxspace=4096
